apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://bitbucket.seiitra.com/scm/gop/argocd-app-config.git
    targetRevision: master
    path: dev
  destination: 
    server: https://kubernetes.default.svc ## the kubernetes API server
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated: # enable auto sync (by default is disabled)
      selfHeal: true # Undo/override any manual changes to the cluster
      prune: true # if a component is deleted/renamed on the yaml file, argocd will also delete it