apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-apps
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/AllaouaA/demo-argocd.git
    targetRevision: main
    path: app-set/appset
  destination: 
    server: https://kubernetes.default.svc ## the kubernetes API server
    namespace: argocd

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated: # enable auto sync (by default is disabled)
      selfHeal: true # Undo/override any manual changes to the cluster
      prune: true # if a component is deleted/renamed on the yaml file, argocd will also delete it